### ISSUE TITLE
Log entry end not getting identified

### ISSUE THREAD

**Issue by adixon** [adixon/ca.civicrm.logviewer#23]
I'm seeing two potential side effects of [this change](https://github.com/adixon/ca.civicrm.logviewer/pull/20) on a couple of sites, seemingly connected (in my mind).

1. The next/prev links aren't showing up.
2. I'm seeing all subsequent entries when trying to look at a single entry.

So I think that means the LogViewEntry.php is no longer recognizing where it's entry finishes.

**Comment by demeritcowboy** [comment]
Oh I think I see it - it's looking for mythical hundredths of a second: `[0-9]{2}:[0-9]{2}:[0-9]{2}:[0-9]{2}`
Going to test something.

**Comment by adixon** [comment]
Thanks, this looks like it worked.
