### ISSUE TITLE
can not read error log

### ISSUE THREAD

**Issue by nickchu852** [adixon/ca.civicrm.logviewer#28]
The current time is 2024-06-27 16:47:53.

Unable to read entries from logfile at /var/www/xxxxxxx/web/sites/default/files/civicrm/ConfigAndLog/CiviCRM.1.xxxxxxxxxxxxxxxx.log

have file "CiviCRM.1.xxxxxxxxxxxxxxxx.log" in /var/www/xxxxxxx/web/sites/default/files/civicrm/ConfigAndLog/，but can not read any thing

**Comment by adixon** [comment]
File permissions issue?

**Comment by adixon** [comment]
I guess I'll close this, but it does remind me that it might be nice if this extension could look at log files other than the 'current' one. A good example is that (sometimes?) command line invocation errors (e.g. cv via a cron job) sometimes go in a different log file than the ones generated by a browser/https invocation. And including older files is also useful when trying to analyse recurring occasional issues that might be getting crowded out by other errors and notices.
